### ISSUE TITLE
[BOUNTY $25] JVM crash when using multi-dimensional local arrays

### ISSUE THREAD

**Issue by raner** [Syncleus/aparapi#51] opened 2017-07-17 08:45 UTC
This may be a user error, since I'm relatively new to both Aparapi and OpenCL, but it seems to me that there is a problem related to multidimensional local arrays.

When I'm executing the kernel shown at https://github.com/raner/top.java.matrix/blob/syncleus-aparapi-issue-51/src/main/java/top/java/matrix/fast/TiledFastMatrix.java#L72 on my MacBook Air (Mac OS X 10.11, Intel HD Graphics 6000 with 48 execution units), I'm consistently getting a JVM crash:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011b42650c, pid=88211, tid=5891
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libaparapi_x86_643808666101765060573.dylib+0xd50c]  KernelArg::setLocalBufferArg(JNIEnv_*, int, int, bool)+0x3c
```
The relevant snippet in the generated OpenCL code seems to be
```
            int tiledRow = (this->val$TILE_SIZE * tile) + localRow;
            int tiledColumn = (this->val$TILE_SIZE * tile) + localColumn;
            (&this->tileA[localColumn * this->tileA__javaArrayDimension0])[localRow]  = this->val$A[((tiledColumn * this->val$numberOfRows) + row)];
            (&this->tileB[localColumn * this->tileB__javaArrayDimension0])[localRow]  = this->val$B[((column * this->val$numberOfColumns) + tiledRow)];
            barrier(CLK_LOCAL_MEM_FENCE);
            for (int repeat = 0; repeat<this->val$TILE_SIZE; repeat++){
               value = value + ((&this->tileA[repeat * this->tileA__javaArrayDimension0])[localRow] * (&this->tileB[localColumn * this->tileB__javaArrayDimension0])[repeat]);
            }
            barrier(CLK_LOCAL_MEM_FENCE);
```
I noticed that it refers to the arrays' dimensions as `tile…__javaArrayDimension0` to calculate the proper index into the two-dimensional array, which, I believe, is what necessitates the earlier invocation of `KernelArg::setLocalBufferArg`. Anyway, I didn't have the time to do a deep dive on this issue, but when I change the arrays to one-dimensional arrays and perform the index calculation myself (as shown in https://github.com/raner/top.java.matrix/commit/cb4988d), the code will work correctly.

**Comment by freemo** [comment] 2017-07-18 07:35
@raner could you simplify this code down to its most basic form that causes the bug and submit it as a unit test? I can then use that to address the issue and work on a fix.

**Comment by raner** [comment] 2017-07-19 06:42
Here's a JUnit test:
```
import static org.junit.Assert.assertEquals;

import org.junit.Test;

import com.aparapi.Kernel;
import com.aparapi.Range;

public class Issue51Test
{
    @Test
    public void passingTest()
    {
        final int SIZE = 16;
        final float[] RESULT = new float[] {1};
        Kernel kernel = new Kernel()
        {
            @Local final float[] localArray = new float[SIZE*SIZE];

            @Override
            public void run()
            {
                int row = getGlobalId(0);
                int column = getGlobalId(1);
                localArray[row + column*SIZE] = row + column;
                localBarrier();
                float value = 0;
                for (int x = 0; x < SIZE; x++)
                {
                    for (int y = 0; y < SIZE; y++)
                    {
                        value += localArray[x + y*SIZE];
                    }
                }
                RESULT[0] = value;
            }
        };
        kernel.execute(Range.create2D(SIZE, SIZE, SIZE, SIZE));
        assertEquals(3840, RESULT[0], 1E-6F);
    }

    @Test
    public void crashingTest()
    {
        final int SIZE = 16;
        final float[] RESULT = new float[] {1};
        Kernel kernel = new Kernel()
        {
            @Local final float[][] localArray = new float[SIZE][SIZE];

            @Override
            public void run()
            {
                int row = getGlobalId(0);
                int column = getGlobalId(1);
                localArray[row][column] = row + column;
                localBarrier();
                float value = 0;
                for (int x = 0; x < SIZE; x++)
                {
                    for (int y = 0; y < SIZE; y++)
                    {
                        value += localArray[x][y];
                    }
                }
                RESULT[0] = value;
            }
        };
        kernel.execute(Range.create2D(SIZE, SIZE, SIZE, SIZE));
        assertEquals(3840, RESULT[0], 1E-6F);
    }
}
```

**Comment by freemo** [comment] 2017-10-21 17:09
@raner I'm going to try to add a bounty to have this resolved. In the meantime we have a PR coming through ( #58 ) which allows for private memory instantiation of arrays (including multidimensional) that may be a work around for you.

**Comment by freemo** [comment] 2018-04-19 17:56
The unit test which demonstrates this bug has been added here:

https://github.com/Syncleus/aparapi/blob/master/src/test/java/com/aparapi/runtime/MultiDimensionalLocalArrayTest.java

**Comment by CoreRasurae** [comment] 2018-04-24 15:53
@fremo This is an aparapi-native bug. OpenCL does not support 2D arrays, so all arrays are mapped from Java 2D or 3D arrays (4D arrays and more n-dimensional are not supported) to 1D array in Aparapi and back. Apparently local arrays with 2D and 3D dimensions were never tested or properly implementend in aparapi-native.

**Comment by freemo** [comment] 2018-04-24 15:55
@CoreRasurae Thanks, useful info for anyone trying to tackle this bug.

**Comment by CoreRasurae** [comment] 2018-04-24 15:56
@freemo It also happens that using 2D or 3D arrays hurts a bit Aparapi perfomance, because Java does not allocate a contiguous memory region for 2D and 3D arrays, instead it allocates bunches of 1D arrays, and thus are non-contiguous in memory. In the name of compatibility Aparapi hides this at the cost of performance.

**Comment by CoreRasurae** [comment] 2018-04-24 15:57
@freemo I will submit a PR for this in aparapi-native, already have it solved.

**Comment by freemo** [comment] 2018-04-24 15:58
@CoreRasurae awesome, thanks. I wish there was an easy way to move tickets between projects. But i suppose since there isnt it makes sense to keep most of the tickets here.

**Comment by CoreRasurae** [comment] 2018-04-24 15:58
@freemo BTW JVM is crashing due to a null pointer de-referencing in aparpi-native.

**Comment by freemo** [comment] 2018-04-24 16:00
@CoreRasurae Neither me nor travis have come across that problem. Can you
create a ticket with any details and, ideally, sample code or a unit test
that recreates it?

**Comment by CoreRasurae** [comment] 2018-04-24 16:24
@freemo That null pointer is the cause of the JVM crash reported by this issue, although the problem is deeper than that.

**Comment by freemo** [comment] 2018-04-24 21:35
This appears to be fixed, closing for now.@raner and @CoreRasurae thank you for your contributions.

**Closed by freemo** 2018-04-24 21:35 UTC
Labels: Bounty $$$, bug
