### ISSUE TITLE
Forgotten git conflict in javadoc

### ISSUE THREAD

**Issue by Vineg** [Syncleus/aparapi#72] opened 2017-10-23 09:20 UTC
https://github.com/Syncleus/aparapi/blob/30f993ab1cc1918ef57369173ff18be0c03747c6/src/main/java/com/aparapi/Kernel.java#L376

**Comment by freemo** [comment] 2017-10-24 04:58
@Vineg Thanks so much for reputing this. This is actually a duplicate of ticket #49 Its part of the 1.5.0 milestone to have it fixed and I will be fixing it this week. As such ill close this ticket and leave #49 open as the authoritative ticket which i will only close once this is officially resolved. Thank you though for reporting this and keep em' coming.

**Closed by freemo** 2017-10-24 04:58 UTC
